{
	"openapi": "3.0.3",
	"info": {
		"title": "Growtweet",
		"description": "Bem-vindo ao Growtweet, a plataforma inovadora para compartilhar suas ideias e conectar-se com o mundo.",
		"contact": {
			"name": "Linkedin",
			"url": "https://www.linkedin.com/in/johann-patr%C3%ADcio-daniel-112425196/"
		},
		"version": "1.0.1"
	},
	"servers": [
		{
			"url": "http://localhost:1807"
		}
	],
	"tags": [
		{
			"name": "Login",
			"description": "Autentique-se de forma segura e acesse sua conta com facilidade."
		},
		{
			"name": "Logout",
			"description": "Encerre sua sessão de maneira rápida e prática."
		},
		{
			"name": "Users",
			"description": "Gerencie suas informações e interaja com a comunidade de forma única."
		},
		{
			"name": "Tweets",
			"description": "Compartilhe seus pensamentos e atualizações em tempo real."
		},
		{
			"name": "Likes",
			"description": "Expresse seu apreço e curta os conteúdos que te inspiram."
		},
		{
			"name": "Replies",
			"description": "Converse e conecte-se através de respostas envolventes."
		},
		{
			"name": "Followers",
			"description": "Acompanhe e seja acompanhado por pessoas que compartilham dos mesmos interesses."
		}
	],
	"paths": {
		"/login": {
			"post": {
				"tags": ["Login"],
				"summary": "Autenticação do usuário",
				"description": "Este endpoint permite que um usuário faça login no sistema utilizando seu e-mail e senha.",
				"requestBody": {
					"required": true,
					"description": "Credenciais do usuário para login",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/InfoLogin"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Login efetuado com sucesso",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{ "$ref": "#/components/schemas/APIResponseLogin" },
										{
											"type": "object",
											"properties": {
												"data": {
													"$ref": "#/components/schemas/DataLogin"
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação de entrada",
						"content": {
							"aplication/json": {
								"examples": {
									"Email Obrigatório": {
										"summary": "O campo e-mail não foi fornecido.",
										"value": {
											"success": false,
											"message": "O atributo e-mail é obrigatório!"
										}
									},
									"Senha Obrigatória": {
										"summary": "O campo senha não foi fornecido.",
										"value": {
											"success": false,
											"message": "O atributo senha é obrigatório!"
										}
									},
									"Email Formato Inválido": {
										"summary": "O campo e-mail deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo email deve vir em formato de texto!"
										}
									},
									"Senha Formato Inválido": {
										"summary": "O campo senha deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo senha deve vir em formato de texto!"
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "Erro de autenticação",
						"content": {
							"aplication/json": {
								"examples": {
									"Token Não Fornecido": {
										"summary": "Nenhum token foi enviado no cabeçalho",
										"value": {
											"success": false,
											"message": "Token não fornecido!"
										}
									},
									"Formato Inválido": {
										"summary": "Token enviado no formato incorreto",
										"value": {
											"success": false,
											"message": "Formato do token inválido! Use (Bearer <token>)."
										}
									},
									"Token Inválido": {
										"summary": "O token está ausente ou inválido",
										"value": {
											"success": false,
											"message": "Token inválido!"
										}
									},
									"Token Revogado": {
										"summary": "O token foi revogado e não pode ser usado",
										"value": {
											"success": false,
											"message": "Token inválido! Faça login novamente."
										}
									},
									"Usuário Não Autenticado": {
										"summary": "O token não corresponde a um usuário válido",
										"value": {
											"success": false,
											"message": "Usuário não autenticado!"
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Recurso não encontrado",
						"content": {
							"application/json": {
								"examples": {
									"Credenciais Inválidas": {
										"summary": "E-mail ou senha incorretos",
										"value": {
											"success": false,
											"message": "E-mail ou senha incorretos!"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/logout": {
			"post": {
				"tags": ["Logout"],
				"summary": "Encerrar sessão do usuário",
				"description": "Este endpoint permite que o usuário faça logout do sistema, invalidando o token de autenticação.",
				"responses": {
					"200": {
						"description": "Logout efetuado com sucesso",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/APIResponseLogout"
								}
							}
						}
					},
					"401": {
						"description": "Erro de autenticação",
						"content": {
							"application/json": {
								"examples": {
									"Token Não Fornecido": {
										"summary": "Nenhum token foi enviado no cabeçalho",
										"value": {
											"success": false,
											"message": "Token não fornecido!"
										}
									},
									"Formato Inválido": {
										"summary": "Token enviado no formato incorreto",
										"value": {
											"success": false,
											"message": "Formato do token inválido! Use (Bearer <token>)."
										}
									},
									"Token Inválido": {
										"summary": "O token está ausente ou inválido",
										"value": {
											"success": false,
											"message": "Token inválido!"
										}
									},
									"Token Revogado": {
										"summary": "O token foi revogado e não pode ser usado",
										"value": {
											"success": false,
											"message": "Token inválido! Faça login novamente."
										}
									},
									"Usuário Não Autenticado": {
										"summary": "O token não corresponde a um usuário válido",
										"value": {
											"success": false,
											"message": "Usuário não autenticado!"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/users": {
			"post": {
				"tags": ["Users"],
				"summary": "Criação de um novo usuário",
				"description": "Este endpoint permite cadastrar um novo usuário no sistema.",
				"requestBody": {
					"required": true,
					"description": "Dados do usuário a serem cadastrados.",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/InfoCreateUser"
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "Usuário criado com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseUserCreate"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"$ref": "#/components/schemas/CreateUser"
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Solicitação Ruim",
						"content": {
							"aplication/json": {
								"examples": {
									"Nome é Obrigatório": {
										"summary": "O campo nome não foi fornecido.",
										"value": {
											"success": false,
											"message": "O atributo nome é obrigatório !"
										}
									},
									"E-mail é Obrigatório": {
										"summary": "O campo e-mail não foi fornecido.",
										"value": {
											"success": false,
											"message": "O atributo email é obrigatório !"
										}
									},
									"Username é Obrigatório": {
										"summary": "O campo username não foi fornecido.",
										"value": {
											"success": false,
											"message": "O atributo username é obrigatório !"
										}
									},
									"Senha é Obrigatório": {
										"summary": "O campo senha não foi fornecido.",
										"value": {
											"success": false,
											"message": "O atributo username é obrigatório !"
										}
									},
									"Nome Formato Inválido": {
										"summary": "O campo nome deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo nome deve vir em formato de texto !"
										}
									},
									"Email Formato Inválido": {
										"summary": "O campo e-mail deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo email deve vir em formato de texto !"
										}
									},
									"Username Formato Inválido": {
										"summary": "O campo username deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo username deve vir em formato de texto !"
										}
									},
									"Password Formato Inválido": {
										"summary": "O campo password deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo senha deve vir em formato de texto !"
										}
									},
									"Nome Formato Data Inválido": {
										"summary": "O campo nome deve ter no minimo 3 caracteres.",
										"value": {
											"success": false,
											"message": "O atributo nome deve ter pelo menos 3 caracteres !"
										}
									},
									"E-mail Formato Data Inválido": {
										"summary": "O campo e-mail deve ter (@) e (.com)",
										"value": {
											"success": false,
											"message": "O e-mail deve conter (@) e (.com)"
										}
									},
									"Username Formato Data Inválido": {
										"summary": "O campo username deve ter no minimo 5 caracteres",
										"value": {
											"success": false,
											"message": "O atributo username deve ter pelo menos 5 caracteres !"
										}
									},
									"Password Formato Data Inválido": {
										"summary": "O campo password deve ter no minimo 5 caracteres",
										"value": {
											"success": false,
											"message": "O atributo senha deve ter pelo menos 5 caracteres !"
										}
									}
								}
							}
						}
					},
					"409": {
						"description": "Conflito",
						"content": {
							"application/json": {
								"examples": {
									"Credenciais Inválidas": {
										"summary": "O e-mail já está em uso !",
										"value": {
											"success": false,
											"message": "O e-mail já está em uso !"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			},
			"get": {
				"tags": ["Users"],
				"summary": "Busca usuários com a opção de filtrar pelo e-mail",
				"description": "Este endpoint permite buscar usuários cadastrados. O e-mail pode ser passado como parâmetro de consulta.",
				"parameters": [
					{
						"name": "email",
						"in": "query",
						"description": "Endereço de e-mail do usuário a ser buscado.",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Usuários encontrados com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseUserFindAll"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"type": "array",
													"items": {
														"$ref": "#/components/schemas/CreateUser"
													}
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação de entrada",
						"content": {
							"aplication/json": {
								"examples": {
									"Email Formato Inválido": {
										"summary": "O campo e-mail deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo email deve vir em formato de texto !"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/users/{id}": {
			"get": {
				"tags": ["Users"],
				"summary": "Busca usuário pelo ID",
				"description": "Este endpoint permite buscar um usuário cadastrado através do seu ID único.",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "O ID do usuário a ser buscado. Deve estar no formato UUID.",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Usuário encontrado com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseUserFindOneById"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"$ref": "#/components/schemas/CreateUser"
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação de entrada",
						"content": {
							"aplication/json": {
								"examples": {
									"UUID Formato Inválido": {
										"summary": "O parâmetro fornecido deve ser um UUID.",
										"value": {
											"success": false,
											"message": "Identificador precisa ser um UUID !"
										}
									}
								}
							}
						}
					},
					"403": {
						"description": "Acesso negado",
						"content": {
							"aplication/json": {
								"examples": {
									"Acesso negado": {
										"summary": "O usuário não tem permissão.",
										"value": {
											"success": false,
											"message": "Acesso negado: você não tem permissão para acessar este usuario."
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Usuário não encontrado",
						"content": {
							"aplication/json": {
								"examples": {
									"Acesso negado": {
										"summary": "O usuário não foi encontrado.",
										"value": {
											"success": false,
											"message": "Usuário a ser buscado não encontrado!"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			},
			"put": {
				"tags": ["Users"],
				"summary": "Atualiza um usuário",
				"description": "Este endpoint permite atualizar um usuário existente pelo seu ID.",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "O ID do usuário a ser atualizado. Deve estar no formato UUID.",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				],
				"requestBody": {
					"required": false,
					"description": "Dados do usuário a serem atualizados.",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/InfoUpdateUser"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Usuário atualizado com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseUserUpdate"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"$ref": "#/components/schemas/UpdateUser"
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação de entrada",
						"content": {
							"aplication/json": {
								"examples": {
									"Nome Formato Inválido": {
										"summary": "O campo nome deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo nome deve vir em formato de texto !"
										}
									},
									"Username Formato Inválido": {
										"summary": "O campo username deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo username deve vir em formato de texto !"
										}
									},
									"Password Formato Inválido": {
										"summary": "O campo password deve ser uma string válida.",
										"value": {
											"success": false,
											"message": "O atributo senha deve vir em formato de texto !"
										}
									},
									"Nome Formato Data Inválido": {
										"summary": "O campo nome deve ter no minimo 3 caracteres.",
										"value": {
											"success": false,
											"message": "O atributo nome deve ter pelo menos 3 caracteres !"
										}
									},
									"Username Formato Data Inválido": {
										"summary": "O campo username deve ter no minimo 5 caracteres",
										"value": {
											"success": false,
											"message": "O atributo username deve ter pelo menos 5 caracteres !"
										}
									},
									"Password Formato Data Inválido": {
										"summary": "O campo password deve ter no minimo 5 caracteres",
										"value": {
											"success": false,
											"message": "O atributo senha deve ter pelo menos 5 caracteres !"
										}
									},
									"UUID Formato Inválido": {
										"summary": "O parâmetro fornecido deve ser um UUID.",
										"value": {
											"success": false,
											"message": "Identificador precisa ser um UUID !"
										}
									}
								}
							}
						}
					},
					"403": {
						"description": "Acesso negado",
						"content": {
							"aplication/json": {
								"examples": {
									"Acesso negado": {
										"summary": "O usuário não tem permissão.",
										"value": {
											"success": false,
											"message": "Acesso negado: você não tem permissão para acessar este usuario."
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Usuário a ser atualizado não encontrado.",
						"content": {
							"application/json": {
								"examples": {
									"Usuário Não Encontrado": {
										"summary": "O ID do usuário não existe no banco de dados",
										"value": {
											"success": false,
											"message": "Usuário a ser atualizado não encontrado !"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			},
			"delete": {
				"tags": ["Users"],
				"summary": "Deleta um usuário",
				"description": "Este endpoint permite deletar um usuário pelo seu ID. Retorna os dados do usuário que foi removido.",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "O ID do usuário a ser deletado. Deve estar no formato UUID.",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Usuário deletado com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseUserRemove"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"$ref": "#/components/schemas/UpdateUser"
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro na requisição.",
						"content": {
							"application/json": {
								"examples": {
									"ID Inválido": {
										"summary": "O ID fornecido não está no formato correto",
										"value": {
											"success": false,
											"message": "Identificador precisa ser um UUID !"
										}
									}
								}
							}
						}
					},
					"403": {
						"description": "Acesso negado.",
						"content": {
							"application/json": {
								"examples": {
									"Acesso negado": {
										"summary": "Acesso negado: você não tem permissão para deletar este usuario.",
										"value": {
											"success": false,
											"message": "Acesso negado: você não tem permissão para deletar este usuario."
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Usuário não encontrado.",
						"content": {
							"application/json": {
								"examples": {
									"Usuário Não Encontrado": {
										"summary": "O ID do usuário não existe no banco de dados",
										"value": {
											"success": false,
											"message": "Usuario a ser deletado não encontrado !"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/tweets": {
			"post": {
				"tags": ["Tweets"],
				"summary": "Cria um novo tweet",
				"description": "Este endpoint permite criar um novo tweet no sistema.",
				"requestBody": {
					"required": true,
					"description": "Dados necessários para criar um tweet.",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/InfoCreateTweet"
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "Tweet criado com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseTweetCreate"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"$ref": "#/components/schemas/CreateTweet"
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro na requisição devido a dados inválidos.",
						"content": {
							"application/json": {
								"examples": {
									"Conteúdo Obrigatório": {
										"summary": "O campo conteúdo é obrigatório.",
										"value": {
											"success": false,
											"message": "O atributo 'content' é obrigatório!"
										}
									},
									"Conteúdo Formato Errado": {
										"summary": "O campo conteúdo deve ser uma string.",
										"value": {
											"success": false,
											"message": "O atributo 'content' deve vir em formato de texto!"
										}
									},
									"Type Formato Errado": {
										"summary": "O campo 'type' deve ser uma string.",
										"value": {
											"success": false,
											"message": "O atributo 'type' deve vir em formato de texto!"
										}
									},
									"Conteúdo Tamanho Inválido": {
										"summary": "O campo conteúdo deve ter pelo menos 5 caracteres.",
										"value": {
											"success": false,
											"message": "O atributo 'content' deve ter pelo menos 5 caracteres!"
										}
									},
									"Type Inválido": {
										"summary": "O campo 'type' só aceita 'Tweet'.",
										"value": {
											"success": false,
											"message": "O atributo 'type' deve ser 'Tweet'!"
										}
									},
									"UserId Formato Inválido": {
										"summary": "O campo userId deve ser um UUID válido.",
										"value": {
											"success": false,
											"message": "Identificador 'userId' precisa ser um UUID válido!"
										}
									}
								}
							}
						}
					},
					"403": {
						"description": "Usuário sem permissão para criar um tweet.",
						"content": {
							"application/json": {
								"examples": {
									"Acesso Negado": {
										"summary": "O usuário não tem permissão.",
										"value": {
											"success": false,
											"message": "Acesso negado: você não tem permissão para criar um tweet."
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Usuário não encontrado.",
						"content": {
							"application/json": {
								"examples": {
									"Usuário Não Encontrado": {
										"summary": "Nenhum usuário corresponde ao ID fornecido.",
										"value": {
											"success": false,
											"message": "Usuário não encontrado!"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor.",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor.",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			},
			"get": {
				"tags": ["Tweets"],
				"summary": "Obtém todos os tweets",
				"description": "Retorna uma lista de tweets, podendo ser filtrada pelo tipo. Se nenhum tipo for especificado, retorna todos os tweets.",
				"parameters": [
					{
						"name": "type",
						"in": "query",
						"description": "Filtra os tweets pelo tipo. Valores aceitos: 'Tweet'.",
						"schema": {
							"type": "string",
							"enum": ["Tweet"]
						}
					}
				],
				"responses": {
					"200": {
						"description": "Lista de tweets recuperada com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseTweetFindAll"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"type": "array",
													"items": {
														"$ref": "#/components/schemas/CreateTweet"
													}
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação no parâmetro 'type'.",
						"content": {
							"application/json": {
								"examples": {
									"Tipo inválido": {
										"summary": "Tipo informado não é válido.",
										"value": {
											"success": false,
											"message": "Tipo inválido fornecido: 'Reply'. Os tipos válidos são: 'Tweet'."
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"tweets/{id}": {
			"get": {
				"tags": ["Tweets"],
				"summary": "Busca um tweet pelo ID",
				"description": "Este endpoint retorna os detalhes de um tweet específico com base no ID fornecido na URL.",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "O UUID do tweet a ser recuperado.",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Tweet recuperado com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/CreateTweet"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"$ref": "#/components/schemas/CreateTweet"
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação nos dados enviados.",
						"content": {
							"application/json": {
								"examples": {
									"UUID Formato Inválido": {
										"summary": "O parâmetro fornecido deve ser um UUID.",
										"value": {
											"success": false,
											"message": "Identificador precisa ser um UUID válido!"
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "Erro de autenticação",
						"content": {
							"application/json": {
								"examples": {
									"Token Não Fornecido": {
										"summary": "Nenhum token foi enviado no cabeçalho",
										"value": {
											"success": false,
											"message": "Token não fornecido!"
										}
									},
									"Formato Inválido": {
										"summary": "Token enviado no formato incorreto",
										"value": {
											"success": false,
											"message": "Formato do token inválido! Use (Bearer <token>)."
										}
									},
									"Token Inválido": {
										"summary": "O token está ausente ou inválido",
										"value": {
											"success": false,
											"message": "Token inválido!"
										}
									},
									"Token Revogado": {
										"summary": "O token foi revogado e não pode ser usado",
										"value": {
											"success": false,
											"message": "Token inválido! Faça login novamente."
										}
									},
									"Usuário Não Autenticado": {
										"summary": "O token não corresponde a um usuário válido",
										"value": {
											"success": false,
											"message": "Usuário não autenticado!"
										}
									}
								}
							}
						}
					},
					"403": {
						"description": "Acesso negado",
						"content": {
							"application/json": {
								"examples": {
									"Acesso negado": {
										"summary": "O usuário não tem permissão para acessar este tweet.",
										"value": {
											"success": false,
											"message": "Acesso negado: você não tem permissão para acessar este tweet."
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Tweet não encontrado",
						"content": {
							"application/json": {
								"examples": {
									"Tweet Não Encontrado": {
										"summary": "Nenhum tweet encontrado com este ID.",
										"value": {
											"success": false,
											"message": "Tweet não encontrado!"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			},
			"put": {
				"tags": ["Tweets"],
				"summary": "Atualiza um tweet existente",
				"description": "Este endpoint permite a atualização de um tweet existente com base no ID fornecido.",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "O UUID do tweet que será atualizado.",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				],
				"requestBody": {
					"required": true,
					"description": "Dados atualizados do tweet.",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/InfoCreateTweet"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Tweet atualizado com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseTweetUpdate"
										},
										{
											"type": "object",
											"properties": {
												"data": {
													"$ref": "#/components/schemas/UpdateTweet"
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação nos dados enviados.",
						"content": {
							"application/json": {
								"examples": {
									"Conteúdo Formato Errado": {
										"summary": "O campo conteúdo deve ser do tipo string.",
										"value": {
											"success": false,
											"message": "O atributo 'content' deve ser uma string!"
										}
									},
									"Conteúdo Tamanho Inválido": {
										"summary": "O campo conteúdo deve ter pelo menos 5 caracteres.",
										"value": {
											"success": false,
											"message": "O atributo 'content' deve ter pelo menos 5 caracteres!"
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "Erro de autenticação",
						"content": {
							"application/json": {
								"examples": {
									"Token Não Fornecido": {
										"summary": "Nenhum token foi enviado no cabeçalho",
										"value": {
											"success": false,
											"message": "Token não fornecido!"
										}
									},
									"Formato Inválido": {
										"summary": "Token enviado no formato incorreto",
										"value": {
											"success": false,
											"message": "Formato do token inválido! Use (Bearer <token>)."
										}
									},
									"Token Inválido": {
										"summary": "O token está ausente ou inválido",
										"value": {
											"success": false,
											"message": "Token inválido!"
										}
									},
									"Token Revogado": {
										"summary": "O token foi revogado e não pode ser usado",
										"value": {
											"success": false,
											"message": "Token inválido! Faça login novamente."
										}
									},
									"Usuário Não Autenticado": {
										"summary": "O token não corresponde a um usuário válido",
										"value": {
											"success": false,
											"message": "Usuário não autenticado!"
										}
									}
								}
							}
						}
					},
					"403": {
						"description": "Acesso negado",
						"content": {
							"application/json": {
								"examples": {
									"Acesso negado": {
										"summary": "O usuário não tem permissão para atualizar este tweet.",
										"value": {
											"success": false,
											"message": "Acesso negado: você não tem permissão para modificar este tweet."
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			},
			"delete": {
				"tags": ["Tweets"],
				"summary": "Remove um tweet pelo ID",
				"description": "Este endpoint permite deletar um tweet específico pelo seu identificador único (UUID). Apenas o autor do tweet pode removê-lo.",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "O UUID do tweet a ser removido.",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Tweet removido com sucesso.",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/APIResponseTweetRemove"
										},
										{
											"type": "object",
											"properties": {
												"message": {
													"type": "string",
													"example": "Tweet removido com sucesso."
												}
											}
										}
									]
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação no parâmetro 'id'.",
						"content": {
							"application/json": {
								"examples": {
									"UUID Formato Inválido": {
										"summary": "O parâmetro fornecido deve ser um UUID válido.",
										"value": {
											"success": false,
											"message": "Identificador precisa ser um UUID válido!"
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "Erro de autenticação",
						"content": {
							"application/json": {
								"examples": {
									"Token Não Fornecido": {
										"summary": "Nenhum token foi enviado no cabeçalho.",
										"value": {
											"success": false,
											"message": "Token não fornecido!"
										}
									},
									"Formato Inválido": {
										"summary": "Token enviado no formato incorreto.",
										"value": {
											"success": false,
											"message": "Formato do token inválido! Use (Bearer <token>)."
										}
									},
									"Token Inválido": {
										"summary": "O token está ausente ou inválido.",
										"value": {
											"success": false,
											"message": "Token inválido!"
										}
									},
									"Token Revogado": {
										"summary": "O token foi revogado e não pode ser usado.",
										"value": {
											"success": false,
											"message": "Token inválido! Faça login novamente."
										}
									},
									"Usuário Não Autenticado": {
										"summary": "O token não corresponde a um usuário válido.",
										"value": {
											"success": false,
											"message": "Usuário não autenticado!"
										}
									}
								}
							}
						}
					},
					"403": {
						"description": "Acesso negado.",
						"content": {
							"application/json": {
								"examples": {
									"Acesso Negado": {
										"summary": "O usuário não tem permissão para deletar este tweet.",
										"value": {
											"success": false,
											"message": "Acesso negado: você não tem permissão para deletar este tweet."
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno no servidor.",
						"content": {
							"application/json": {
								"examples": {
									"Erro no Servidor": {
										"summary": "Ocorreu um erro inesperado no servidor.",
										"value": {
											"success": false,
											"message": "Erro no servidor: descrição do erro."
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/likes": {
			"post": {
				"tags": ["Likes"]
			}
		},
		"/likes/{id}": {
			"delete": {
				"tags": ["Likes"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				]
			}
		},
		"/replies": {
			"post": {
				"tags": ["Replies"],
				"summary": "",
				"description": "",
				"requestBody": {
					"required": true,
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": ""
							}
						}
					}
				}
			},
			"get": {
				"tags": ["Replies"],
				"parameters": [
					{
						"name": "type",
						"in": "query",
						"description": "",
						"schema": {
							"type": "string"
						}
					}
				]
			}
		},
		"/replies/{id}": {
			"get": {
				"tags": ["Replies"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				]
			},
			"put": {
				"tags": ["Replies"],
				"summary": "",
				"description": "",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				],
				"requestBody": {
					"required": true,
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": ""
							}
						}
					}
				}
			},
			"delete": {
				"tags": ["Replies"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				]
			}
		},
		"/followers": {
			"post": {
				"tags": ["Followers"]
			}
		},
		"/followers/{id}": {
			"delete": {
				"tags": ["Followers"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"description": "",
						"schema": {
							"type": "string",
							"format": "uuid"
						}
					}
				]
			}
		}
	},
	"components": {
		"schemas": {
			"InfoLogin": {
				"type": "object",
				"properties": {
					"email": {
						"type": "string",
						"example": "joao.silva@email.com"
					},
					"password": {
						"type": "string",
						"example": "senha123"
					}
				},
				"required": ["email", "password"]
			},
			"InfoCreateUser": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string",
						"example": "João Silva"
					},
					"email": {
						"type": "string",
						"format": "email",
						"example": "joao.silva@email.com"
					},
					"username": {
						"type": "string",
						"example": "joaosilva"
					},
					"password": {
						"type": "string",
						"example": "senha123"
					}
				},
				"required": ["name", "email", "username", "password"]
			},
			"InfoUpdateUser": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string",
						"example": "Maria Paula da Silva"
					},
					"username": {
						"type": "string",
						"example": "maria123"
					},
					"password": {
						"type": "string",
						"example": "senha321"
					}
				}
			},
			"InfoCreateTweet": {
				"type": "object",
				"properties": {
					"content": {
						"type": "string",
						"example": "Mensagem 1"
					},
					"type": {
						"type": "string",
						"example": "Tweet"
					}
				},
				"required": ["content", "type"]
			},
			"APIResponseLogin": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "object",
						"example": "Login efetuado com sucesso"
					}
				}
			},
			"APIResponseLogout": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "object",
						"example": "Logout efetuado com sucesso!"
					}
				}
			},
			"DataLogin": {
				"type": "object",
				"properties": {
					"token": {
						"type": "string",
						"example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ..."
					},
					"userId": {
						"type": "string",
						"format": "uuid",
						"example": "653ae26b-7fe6-4312-9a94-cea7aeae4079"
					},
					"tweetId": {
						"type": "string",
						"format": "uuid",
						"example": "550e8400-e29b-41d4-a716-446655440000"
					},
					"followerId": {
						"type": "array",
						"items": {
							"type": "string",
							"format": "uuid"
						},
						"example": [
							"550e8400-e29b-41d4-a716-446655440000",
							"653ae26b-7fe6-4312-9a94-cea7aeae4079"
						]
					}
				},
				"required": ["token", "userId"]
			},
			"APIResponseUserCreate": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Usuário criado com sucesso !"
					}
				}
			},
			"APIResponseUserFindAll": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Usuários buscado com sucesso !"
					}
				}
			},
			"APIResponseUserFindOneById": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Usuário buscado pelo id com sucesso!"
					}
				}
			},
			"APIResponseUserUpdate": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Usuário atualizado com sucesso !"
					}
				}
			},
			"APIResponseUserRemove": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Usuário deletado com sucesso !"
					}
				}
			},
			"APIResponseTweetCreate": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Tweet criado com sucesso !"
					}
				}
			},
			"APIResponseTweetFindAll": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Tweets buscados com sucesso!"
					}
				}
			},
			"APIResponseTweetUpdate": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Tweet atualizado com sucesso!"
					}
				}
			},
			"APIResponseTweetRemove": {
				"type": "object",
				"properties": {
					"success": {
						"type": "boolean",
						"example": true
					},
					"message": {
						"type": "string",
						"example": "Tweet deletado com sucesso!"
					}
				}
			},
			"CreateUser": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string",
						"example": "João Silva"
					},
					"email": {
						"type": "string",
						"format": "email",
						"example": "joao.silva@email.com"
					},
					"username": {
						"type": "string",
						"example": "joaosilva"
					},
					"createdAt": {
						"type": "string",
						"example": "2024-02-01T12:30:45Z"
					}
				}
			},
			"UpdateUser": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string",
						"example": "Maria Paula da Silva"
					},
					"username": {
						"type": "string",
						"example": "maria123"
					},
					"createdAt": {
						"type": "string",
						"example": "2024-02-01T12:30:45Z"
					}
				}
			},
			"CreateTweet": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"format": "uuid",
						"description": "Identificador único do tweet"
					},
					"content": {
						"type": "string",
						"example": "Essa é uma mensagem de exemplo",
						"description": "Conteúdo do tweet"
					},
					"type": {
						"type": "string",
						"example": "Tweet",
						"description": "Tipo da publicação (ex: Tweet, Reply, etc.)"
					},
					"createdAt": {
						"type": "string",
						"format": "date-time",
						"example": "2024-02-02T12:34:56Z",
						"description": "Data e hora de criação do tweet no formato ISO 8601"
					}
				},
				"required": ["id", "content", "type", "createdAt"]
			},
			"UpdateTweet": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"format": "uuid",
						"description": "Identificador único do tweet"
					},
					"content": {
						"type": "string",
						"example": "Essa é uma mensagem de exemplo atualizada",
						"description": "Conteúdo do tweet"
					},
					"type": {
						"type": "string",
						"example": "Tweet",
						"description": "Tipo da publicação (ex: Tweet, Reply, etc.)"
					},
					"createdAt": {
						"type": "string",
						"format": "date-time",
						"example": "2024-02-02T12:34:56Z",
						"description": "Data e hora de criação do tweet no formato ISO 8601"
					}
				},
				"required": ["id", "createdAt"]
			}
		}
	}
}
